# This file was generated by ModelOS
from __future__ import annotations
from modelos import Object
from typing import Iterable


class Foo(Object):
    """A classic Foo"""

    id: str
    amount: int

    def __init__(self, id: str, amount: int) -> None:
        self.id = id
        self.amount = amount

    def add(self, amount: int) -> None:
        self.amount += amount

    def echo(self, s: str) -> str:
        return f"hello {s}"

    def stream(self, s: str) -> Iterable[str]:
        for i in range(self.amount):
            yield f"hello {s} {i}"
